const VCT2026_DATA = {
  "summary": {
    "tournaments": 5,
    "players": 244,
    "teams": 49,
    "matches": 139,
    "maps": 379
  },
  "teams": [
    {
      "name": "Wolves Esports",
      "match_played": 5,
      "match_won": 2,
      "match_win_pct": 40.0,
      "map_played": 14,
      "map_won": 6,
      "map_win_pct": 42.86,
      "pistol_played": 0,
      "pistol_won": 0,
      "pistol_win_pct": 0.0,
      "clutch_played": 0,
      "clutch_won": 0,
      "clutch_win_pct": 0.0,
      "thrifty_wins": 0
    },
    {
      "name": "Paper Rex",
      "match_played": 15,
      "match_won": 11,
      "match_win_pct": 73.33,
      "map_played": 43,
      "map_won": 25,
      "map_win_pct": 58.14,
      "pistol_played": 86,
      "pistol_won": 47,
      "pistol_win_pct": 54.65,
      "clutch_played": 1852,
      "clutch_won": 205,
      "clutch_win_pct": 11.07,
      "thrifty_wins": 50
    },
    {
      "name": "Nongshim RedForce",
      "match_played": 8,
      "match_won": 8,
      "match_win_pct": 100.0,
      "map_played": 22,
      "map_won": 18,
      "map_win_pct": 81.82,
      "pistol_played": 44,
      "pistol_won": 28,
      "pistol_win_pct": 63.64,
      "clutch_played": 789,
      "clutch_won": 141,
      "clutch_win_pct": 17.87,
      "thrifty_wins": 33
    },
    {
      "name": "Trace Esports",
      "match_played": 5,
      "match_won": 2,
      "match_win_pct": 40.0,
      "map_played": 13,
      "map_won": 5,
      "map_win_pct": 38.46,
      "pistol_played": 0,
      "pistol_won": 0,
      "pistol_win_pct": 0.0,
      "clutch_played": 0,
      "clutch_won": 0,
      "clutch_win_pct": 0.0,
      "thrifty_wins": 0
    },
    {
      "name": "GIANTX",
      "match_played": 5,
      "match_won": 2,
      "match_win_pct": 40.0,
      "map_played": 12,
      "map_won": 5,
      "map_win_pct": 41.67,
      "pistol_played": 24,
      "pistol_won": 14,
      "pistol_win_pct": 58.33,
      "clutch_played": 608,
      "clutch_won": 124,
      "clutch_win_pct": 20.39,
      "thrifty_wins": 17
    },
    {
      "name": "LEVIAT\u00c1N",
      "match_played": 5,
      "match_won": 2,
      "match_win_pct": 40.0,
      "map_played": 11,
      "map_won": 5,
      "map_win_pct": 45.45,
      "pistol_played": 22,
      "pistol_won": 16,
      "pistol_win_pct": 72.73,
      "clutch_played": 470,
      "clutch_won": 63,
      "clutch_win_pct": 13.4,
      "thrifty_wins": 16
    },
    {
      "name": "VARREL",
      "match_played": 3,
      "match_won": 0,
      "match_win_pct": 0.0,
      "map_played": 8,
      "map_won": 2,
      "map_win_pct": 25.0,
      "pistol_played": 16,
      "pistol_won": 4,
      "pistol_win_pct": 25.0,
      "clutch_played": 453,
      "clutch_won": 63,
      "clutch_win_pct": 13.91,
      "thrifty_wins": 6
    },
    {
      "name": "Team Vitality",
      "match_played": 6,
      "match_won": 3,
      "match_win_pct": 50.0,
      "map_played": 14,
      "map_won": 7,
      "map_win_pct": 50.0,
      "pistol_played": 28,
      "pistol_won": 11,
      "pistol_win_pct": 39.29,
      "clutch_played": 574,
      "clutch_won": 76,
      "clutch_win_pct": 13.24,
      "thrifty_wins": 13
    },
    {
      "name": "JDG Esports",
      "match_played": 6,
      "match_won": 3,
      "match_win_pct": 50.0,
      "map_played": 18,
      "map_won": 9,
      "map_win_pct": 50.0,
      "pistol_played": 0,
      "pistol_won": 0,
      "pistol_win_pct": 0.0,
      "clutch_played": 0,
      "clutch_won": 0,
      "clutch_win_pct": 0.0,
      "thrifty_wins": 0
    },
    {
      "name": "FURIA",
      "match_played": 6,
      "match_won": 4,
      "match_win_pct": 66.67,
      "map_played": 19,
      "map_won": 11,
      "map_win_pct": 57.89,
      "pistol_played": 38,
      "pistol_won": 20,
      "pistol_win_pct": 52.63,
      "clutch_played": 791,
      "clutch_won": 128,
      "clutch_win_pct": 16.18,
      "thrifty_wins": 22
    },
    {
      "name": "Team Liquid",
      "match_played": 11,
      "match_won": 7,
      "match_win_pct": 63.64,
      "map_played": 28,
      "map_won": 16,
      "map_win_pct": 57.14,
      "pistol_played": 56,
      "pistol_won": 26,
      "pistol_win_pct": 46.43,
      "clutch_played": 1263,
      "clutch_won": 179,
      "clutch_win_pct": 14.17,
      "thrifty_wins": 30
    },
    {
      "name": "Dragon Ranger Gaming",
      "match_played": 5,
      "match_won": 2,
      "match_win_pct": 40.0,
      "map_played": 14,
      "map_won": 6,
      "map_win_pct": 42.86,
      "pistol_played": 0,
      "pistol_won": 0,
      "pistol_win_pct": 0.0,
      "clutch_played": 0,
      "clutch_won": 0,
      "clutch_win_pct": 0.0,
      "thrifty_wins": 0
    },
    {
      "name": "Evil Geniuses",
      "match_played": 5,
      "match_won": 2,
      "match_win_pct": 40.0,
      "map_played": 11,
      "map_won": 5,
      "map_win_pct": 45.45,
      "pistol_played": 22,
      "pistol_won": 13,
      "pistol_win_pct": 59.09,
      "clutch_played": 472,
      "clutch_won": 48,
      "clutch_win_pct": 10.17,
      "thrifty_wins": 13
    },
    {
      "name": "Sentinels",
      "match_played": 4,
      "match_won": 1,
      "match_win_pct": 25.0,
      "map_played": 8,
      "map_won": 2,
      "map_win_pct": 25.0,
      "pistol_played": 16,
      "pistol_won": 10,
      "pistol_win_pct": 62.5,
      "clutch_played": 388,
      "clutch_won": 53,
      "clutch_win_pct": 13.66,
      "thrifty_wins": 11
    },
    {
      "name": "FULL SENSE",
      "match_played": 5,
      "match_won": 2,
      "match_win_pct": 40.0,
      "map_played": 12,
      "map_won": 5,
      "map_win_pct": 41.67,
      "pistol_played": 24,
      "pistol_won": 9,
      "pistol_win_pct": 37.5,
      "clutch_played": 465,
      "clutch_won": 73,
      "clutch_win_pct": 15.7,
      "thrifty_wins": 9
    },
    {
      "name": "DetonatioN FocusMe",
      "match_played": 7,
      "match_won": 4,
      "match_win_pct": 57.14,
      "map_played": 16,
      "map_won": 8,
      "map_win_pct": 50.0,
      "pistol_played": 32,
      "pistol_won": 17,
      "pistol_win_pct": 53.12,
      "clutch_played": 681,
      "clutch_won": 94,
      "clutch_win_pct": 13.8,
      "thrifty_wins": 18
    },
    {
      "name": "KR\u00dc Esports",
      "match_played": 3,
      "match_won": 0,
      "match_win_pct": 0.0,
      "map_played": 8,
      "map_won": 2,
      "map_win_pct": 25.0,
      "pistol_played": 16,
      "pistol_won": 3,
      "pistol_win_pct": 18.75,
      "clutch_played": 399,
      "clutch_won": 57,
      "clutch_win_pct": 14.29,
      "thrifty_wins": 4
    },
    {
      "name": "100 Thieves",
      "match_played": 8,
      "match_won": 5,
      "match_win_pct": 62.5,
      "map_played": 20,
      "map_won": 11,
      "map_win_pct": 55.0,
      "pistol_played": 40,
      "pistol_won": 14,
      "pistol_win_pct": 35.0,
      "clutch_played": 853,
      "clutch_won": 99,
      "clutch_win_pct": 11.61,
      "thrifty_wins": 20
    },
    {
      "name": "Natus Vincere",
      "match_played": 5,
      "match_won": 2,
      "match_win_pct": 40.0,
      "map_played": 12,
      "map_won": 5,
      "map_win_pct": 41.67,
      "pistol_played": 24,
      "pistol_won": 12,
      "pistol_win_pct": 50.0,
      "clutch_played": 558,
      "clutch_won": 67,
      "clutch_win_pct": 12.01,
      "thrifty_wins": 13
    },
    {
      "name": "FNATIC",
      "match_played": 7,
      "match_won": 4,
      "match_win_pct": 57.14,
      "map_played": 20,
      "map_won": 10,
      "map_win_pct": 50.0,
      "pistol_played": 40,
      "pistol_won": 22,
      "pistol_win_pct": 55.0,
      "clutch_played": 976,
      "clutch_won": 114,
      "clutch_win_pct": 11.68,
      "thrifty_wins": 24
    },
    {
      "name": "FunPlus Phoenix",
      "match_played": 3,
      "match_won": 0,
      "match_win_pct": 0.0,
      "map_played": 7,
      "map_won": 1,
      "map_win_pct": 14.29,
      "pistol_played": 0,
      "pistol_won": 0,
      "pistol_win_pct": 0.0,
      "clutch_played": 0,
      "clutch_won": 0,
      "clutch_win_pct": 0.0,
      "thrifty_wins": 0
    },
    {
      "name": "Rex Regum Qeon",
      "match_played": 5,
      "match_won": 2,
      "match_win_pct": 40.0,
      "map_played": 16,
      "map_won": 7,
      "map_win_pct": 43.75,
      "pistol_played": 32,
      "pistol_won": 12,
      "pistol_win_pct": 37.5,
      "clutch_played": 766,
      "clutch_won": 126,
      "clutch_win_pct": 16.45,
      "thrifty_wins": 15
    },
    {
      "name": "ZETA DIVISION",
      "match_played": 4,
      "match_won": 1,
      "match_win_pct": 25.0,
      "map_played": 10,
      "map_won": 3,
      "map_win_pct": 30.0,
      "pistol_played": 20,
      "pistol_won": 11,
      "pistol_win_pct": 55.0,
      "clutch_played": 424,
      "clutch_won": 40,
      "clutch_win_pct": 9.43,
      "thrifty_wins": 12
    },
    {
      "name": "Nova Esports",
      "match_played": 3,
      "match_won": 0,
      "match_win_pct": 0.0,
      "map_played": 7,
      "map_won": 1,
      "map_win_pct": 14.29,
      "pistol_played": 0,
      "pistol_won": 0,
      "pistol_win_pct": 0.0,
      "clutch_played": 0,
      "clutch_won": 0,
      "clutch_win_pct": 0.0,
      "thrifty_wins": 0
    },
    {
      "name": "Mega Minors",
      "match_played": 13,
      "match_won": 0,
      "match_win_pct": 0.0,
      "map_played": 34,
      "map_won": 20,
      "map_win_pct": 58.82,
      "pistol_played": 68,
      "pistol_won": 39,
      "pistol_win_pct": 57.35,
      "clutch_played": 1459,
      "clutch_won": 219,
      "clutch_win_pct": 15.01,
      "thrifty_wins": 42
    },
    {
      "name": "ENVY",
      "match_played": 5,
      "match_won": 2,
      "match_win_pct": 40.0,
      "map_played": 13,
      "map_won": 5,
      "map_win_pct": 38.46,
      "pistol_played": 26,
      "pistol_won": 14,
      "pistol_win_pct": 53.85,
      "clutch_played": 567,
      "clutch_won": 54,
      "clutch_win_pct": 9.52,
      "thrifty_wins": 15
    },
    {
      "name": "Gen.G",
      "match_played": 4,
      "match_won": 1,
      "match_win_pct": 25.0,
      "map_played": 11,
      "map_won": 4,
      "map_win_pct": 36.36,
      "pistol_played": 22,
      "pistol_won": 9,
      "pistol_win_pct": 40.91,
      "clutch_played": 582,
      "clutch_won": 91,
      "clutch_win_pct": 15.64,
      "thrifty_wins": 12
    },
    {
      "name": "Team Heretics",
      "match_played": 6,
      "match_won": 3,
      "match_win_pct": 50.0,
      "map_played": 14,
      "map_won": 7,
      "map_win_pct": 50.0,
      "pistol_played": 28,
      "pistol_won": 12,
      "pistol_win_pct": 42.86,
      "clutch_played": 634,
      "clutch_won": 85,
      "clutch_win_pct": 13.41,
      "thrifty_wins": 13
    },
    {
      "name": "PCIFIC Esports",
      "match_played": 3,
      "match_won": 0,
      "match_win_pct": 0.0,
      "map_played": 8,
      "map_won": 2,
      "map_win_pct": 25.0,
      "pistol_played": 16,
      "pistol_won": 8,
      "pistol_win_pct": 50.0,
      "clutch_played": 394,
      "clutch_won": 39,
      "clutch_win_pct": 9.9,
      "thrifty_wins": 8
    },
    {
      "name": "Team Secret",
      "match_played": 3,
      "match_won": 0,
      "match_win_pct": 0.0,
      "map_played": 7,
      "map_won": 1,
      "map_win_pct": 14.29,
      "pistol_played": 14,
      "pistol_won": 6,
      "pistol_win_pct": 42.86,
      "clutch_played": 295,
      "clutch_won": 34,
      "clutch_win_pct": 11.53,
      "thrifty_wins": 6
    },
    {
      "name": "TYLOO",
      "match_played": 7,
      "match_won": 4,
      "match_win_pct": 57.14,
      "map_played": 17,
      "map_won": 10,
      "map_win_pct": 58.82,
      "pistol_played": 0,
      "pistol_won": 0,
      "pistol_win_pct": 0.0,
      "clutch_played": 0,
      "clutch_won": 0,
      "clutch_win_pct": 0.0,
      "thrifty_wins": 0
    },
    {
      "name": "Global Esports",
      "match_played": 6,
      "match_won": 3,
      "match_win_pct": 50.0,
      "map_played": 16,
      "map_won": 9,
      "map_win_pct": 56.25,
      "pistol_played": 32,
      "pistol_won": 17,
      "pistol_win_pct": 53.12,
      "clutch_played": 652,
      "clutch_won": 87,
      "clutch_win_pct": 13.34,
      "thrifty_wins": 19
    },
    {
      "name": "Xi Lai Gaming",
      "match_played": 6,
      "match_won": 3,
      "match_win_pct": 50.0,
      "map_played": 18,
      "map_won": 9,
      "map_win_pct": 50.0,
      "pistol_played": 8,
      "pistol_won": 3,
      "pistol_win_pct": 37.5,
      "clutch_played": 174,
      "clutch_won": 12,
      "clutch_win_pct": 6.9,
      "thrifty_wins": 3
    },
    {
      "name": "FUT Esports",
      "match_played": 3,
      "match_won": 0,
      "match_win_pct": 0.0,
      "map_played": 8,
      "map_won": 2,
      "map_win_pct": 25.0,
      "pistol_played": 16,
      "pistol_won": 6,
      "pistol_win_pct": 37.5,
      "clutch_played": 456,
      "clutch_won": 56,
      "clutch_win_pct": 12.28,
      "thrifty_wins": 7
    },
    {
      "name": "Karmine Corp",
      "match_played": 4,
      "match_won": 1,
      "match_win_pct": 25.0,
      "map_played": 11,
      "map_won": 4,
      "map_win_pct": 36.36,
      "pistol_played": 22,
      "pistol_won": 11,
      "pistol_win_pct": 50.0,
      "clutch_played": 499,
      "clutch_won": 71,
      "clutch_win_pct": 14.23,
      "thrifty_wins": 12
    },
    {
      "name": "MIBR",
      "match_played": 5,
      "match_won": 2,
      "match_win_pct": 40.0,
      "map_played": 18,
      "map_won": 8,
      "map_win_pct": 44.44,
      "pistol_played": 36,
      "pistol_won": 12,
      "pistol_win_pct": 33.33,
      "clutch_played": 783,
      "clutch_won": 85,
      "clutch_win_pct": 10.86,
      "thrifty_wins": 12
    },
    {
      "name": "T1",
      "match_played": 9,
      "match_won": 6,
      "match_win_pct": 66.67,
      "map_played": 22,
      "map_won": 14,
      "map_win_pct": 63.64,
      "pistol_played": 44,
      "pistol_won": 25,
      "pistol_win_pct": 56.82,
      "clutch_played": 957,
      "clutch_won": 143,
      "clutch_win_pct": 14.94,
      "thrifty_wins": 27
    },
    {
      "name": "DRX",
      "match_played": 6,
      "match_won": 3,
      "match_win_pct": 50.0,
      "map_played": 16,
      "map_won": 8,
      "map_win_pct": 50.0,
      "pistol_played": 32,
      "pistol_won": 19,
      "pistol_win_pct": 59.38,
      "clutch_played": 683,
      "clutch_won": 112,
      "clutch_win_pct": 16.4,
      "thrifty_wins": 20
    },
    {
      "name": "Titan Esports Club",
      "match_played": 4,
      "match_won": 1,
      "match_win_pct": 25.0,
      "map_played": 12,
      "map_won": 5,
      "map_win_pct": 41.67,
      "pistol_played": 0,
      "pistol_won": 0,
      "pistol_win_pct": 0.0,
      "clutch_played": 0,
      "clutch_won": 0,
      "clutch_win_pct": 0.0,
      "thrifty_wins": 0
    },
    {
      "name": "EDward Gaming",
      "match_played": 9,
      "match_won": 5,
      "match_win_pct": 55.56,
      "map_played": 24,
      "map_won": 12,
      "map_win_pct": 50.0,
      "pistol_played": 8,
      "pistol_won": 5,
      "pistol_win_pct": 62.5,
      "clutch_played": 185,
      "clutch_won": 10,
      "clutch_win_pct": 5.41,
      "thrifty_wins": 5
    },
    {
      "name": "Cloud9",
      "match_played": 7,
      "match_won": 4,
      "match_win_pct": 57.14,
      "map_played": 16,
      "map_won": 9,
      "map_win_pct": 56.25,
      "pistol_played": 32,
      "pistol_won": 13,
      "pistol_win_pct": 40.62,
      "clutch_played": 723,
      "clutch_won": 101,
      "clutch_win_pct": 13.97,
      "thrifty_wins": 15
    },
    {
      "name": "ULF Esports",
      "match_played": 4,
      "match_won": 1,
      "match_win_pct": 25.0,
      "map_played": 9,
      "map_won": 3,
      "map_win_pct": 33.33,
      "pistol_played": 18,
      "pistol_won": 7,
      "pistol_win_pct": 38.89,
      "clutch_played": 438,
      "clutch_won": 72,
      "clutch_win_pct": 16.44,
      "thrifty_wins": 7
    },
    {
      "name": "BBL Esports",
      "match_played": 7,
      "match_won": 5,
      "match_win_pct": 71.43,
      "map_played": 20,
      "map_won": 12,
      "map_win_pct": 60.0,
      "pistol_played": 40,
      "pistol_won": 20,
      "pistol_win_pct": 50.0,
      "clutch_played": 798,
      "clutch_won": 128,
      "clutch_win_pct": 16.04,
      "thrifty_wins": 24
    },
    {
      "name": "LOUD",
      "match_played": 3,
      "match_won": 0,
      "match_win_pct": 0.0,
      "map_played": 7,
      "map_won": 1,
      "map_win_pct": 14.29,
      "pistol_played": 14,
      "pistol_won": 8,
      "pistol_win_pct": 57.14,
      "clutch_played": 352,
      "clutch_won": 40,
      "clutch_win_pct": 11.36,
      "thrifty_wins": 8
    },
    {
      "name": "Gentle Mates",
      "match_played": 9,
      "match_won": 6,
      "match_win_pct": 66.67,
      "map_played": 25,
      "map_won": 16,
      "map_win_pct": 64.0,
      "pistol_played": 50,
      "pistol_won": 28,
      "pistol_win_pct": 56.0,
      "clutch_played": 889,
      "clutch_won": 144,
      "clutch_win_pct": 16.2,
      "thrifty_wins": 32
    },
    {
      "name": "G2 Esports",
      "match_played": 12,
      "match_won": 8,
      "match_win_pct": 66.67,
      "map_played": 29,
      "map_won": 20,
      "map_win_pct": 68.97,
      "pistol_played": 58,
      "pistol_won": 32,
      "pistol_win_pct": 55.17,
      "clutch_played": 1133,
      "clutch_won": 177,
      "clutch_win_pct": 15.62,
      "thrifty_wins": 39
    },
    {
      "name": "Bilibili Gaming",
      "match_played": 7,
      "match_won": 4,
      "match_win_pct": 57.14,
      "map_played": 20,
      "map_won": 11,
      "map_win_pct": 55.0,
      "pistol_played": 0,
      "pistol_won": 0,
      "pistol_win_pct": 0.0,
      "clutch_played": 0,
      "clutch_won": 0,
      "clutch_win_pct": 0.0,
      "thrifty_wins": 0
    },
    {
      "name": "All Gamers",
      "match_played": 7,
      "match_won": 5,
      "match_win_pct": 71.43,
      "map_played": 20,
      "map_won": 12,
      "map_win_pct": 60.0,
      "pistol_played": 16,
      "pistol_won": 7,
      "pistol_win_pct": 43.75,
      "clutch_played": 352,
      "clutch_won": 36,
      "clutch_win_pct": 10.23,
      "thrifty_wins": 7
    }
  ],
  "agents": [
    {
      "name": "astra",
      "pick_rate": 43.4,
      "max_pick_rate": 100.0,
      "avg_rating": 0.99,
      "avg_acs": 181.8,
      "appearances": 1725
    },
    {
      "name": "breach",
      "pick_rate": 4.9,
      "max_pick_rate": 100.0,
      "avg_rating": 0.91,
      "avg_acs": 176.1,
      "appearances": 207
    },
    {
      "name": "brimstone",
      "pick_rate": 14.9,
      "max_pick_rate": 100.0,
      "avg_rating": 1.0,
      "avg_acs": 187.6,
      "appearances": 648
    },
    {
      "name": "chamber",
      "pick_rate": 10.8,
      "max_pick_rate": 100.0,
      "avg_rating": 1.09,
      "avg_acs": 212.4,
      "appearances": 456
    },
    {
      "name": "clove",
      "pick_rate": 0.0,
      "max_pick_rate": 0.0,
      "avg_rating": 0.0,
      "avg_acs": 0.0,
      "appearances": 0
    },
    {
      "name": "cypher",
      "pick_rate": 11.8,
      "max_pick_rate": 100.0,
      "avg_rating": 1.0,
      "avg_acs": 192.6,
      "appearances": 456
    },
    {
      "name": "deadlock",
      "pick_rate": 0.0,
      "max_pick_rate": 0.0,
      "avg_rating": 0.0,
      "avg_acs": 0.0,
      "appearances": 0
    },
    {
      "name": "fade",
      "pick_rate": 36.0,
      "max_pick_rate": 100.0,
      "avg_rating": 0.97,
      "avg_acs": 181.9,
      "appearances": 1386
    },
    {
      "name": "gekko",
      "pick_rate": 1.7,
      "max_pick_rate": 50.0,
      "avg_rating": 0.92,
      "avg_acs": 172.6,
      "appearances": 66
    },
    {
      "name": "harbor",
      "pick_rate": 1.4,
      "max_pick_rate": 50.0,
      "avg_rating": 0.93,
      "avg_acs": 180.5,
      "appearances": 66
    },
    {
      "name": "iso",
      "pick_rate": 1.2,
      "max_pick_rate": 50.0,
      "avg_rating": 0.87,
      "avg_acs": 206.4,
      "appearances": 54
    },
    {
      "name": "jett",
      "pick_rate": 11.8,
      "max_pick_rate": 100.0,
      "avg_rating": 1.04,
      "avg_acs": 222.2,
      "appearances": 510
    },
    {
      "name": "kayo",
      "pick_rate": 9.0,
      "max_pick_rate": 100.0,
      "avg_rating": 1.0,
      "avg_acs": 192.9,
      "appearances": 378
    },
    {
      "name": "killjoy",
      "pick_rate": 14.0,
      "max_pick_rate": 100.0,
      "avg_rating": 0.99,
      "avg_acs": 192.6,
      "appearances": 642
    },
    {
      "name": "miks",
      "pick_rate": 0.0,
      "max_pick_rate": 0.0,
      "avg_rating": 0.0,
      "avg_acs": 0.0,
      "appearances": 0
    },
    {
      "name": "neon",
      "pick_rate": 29.9,
      "max_pick_rate": 100.0,
      "avg_rating": 0.96,
      "avg_acs": 213.4,
      "appearances": 1182
    },
    {
      "name": "omen",
      "pick_rate": 47.5,
      "max_pick_rate": 100.0,
      "avg_rating": 0.97,
      "avg_acs": 185.6,
      "appearances": 1881
    },
    {
      "name": "phoenix",
      "pick_rate": 5.4,
      "max_pick_rate": 100.0,
      "avg_rating": 1.07,
      "avg_acs": 230.7,
      "appearances": 201
    },
    {
      "name": "raze",
      "pick_rate": 15.5,
      "max_pick_rate": 100.0,
      "avg_rating": 1.0,
      "avg_acs": 217.6,
      "appearances": 645
    },
    {
      "name": "reyna",
      "pick_rate": 0.6,
      "max_pick_rate": 50.0,
      "avg_rating": 0.89,
      "avg_acs": 210.0,
      "appearances": 21
    },
    {
      "name": "sage",
      "pick_rate": 2.7,
      "max_pick_rate": 50.0,
      "avg_rating": 1.01,
      "avg_acs": 181.9,
      "appearances": 120
    },
    {
      "name": "skye",
      "pick_rate": 11.4,
      "max_pick_rate": 100.0,
      "avg_rating": 0.92,
      "avg_acs": 172.2,
      "appearances": 495
    },
    {
      "name": "sova",
      "pick_rate": 47.9,
      "max_pick_rate": 100.0,
      "avg_rating": 0.97,
      "avg_acs": 180.8,
      "appearances": 1785
    },
    {
      "name": "tejo",
      "pick_rate": 12.1,
      "max_pick_rate": 100.0,
      "avg_rating": 0.96,
      "avg_acs": 184.4,
      "appearances": 537
    },
    {
      "name": "veto",
      "pick_rate": 6.4,
      "max_pick_rate": 100.0,
      "avg_rating": 1.02,
      "avg_acs": 209.6,
      "appearances": 279
    },
    {
      "name": "viper",
      "pick_rate": 57.4,
      "max_pick_rate": 100.0,
      "avg_rating": 1.02,
      "avg_acs": 199.9,
      "appearances": 2232
    },
    {
      "name": "vyse",
      "pick_rate": 3.9,
      "max_pick_rate": 100.0,
      "avg_rating": 1.12,
      "avg_acs": 214.4,
      "appearances": 132
    },
    {
      "name": "waylay",
      "pick_rate": 38.9,
      "max_pick_rate": 100.0,
      "avg_rating": 0.94,
      "avg_acs": 200.3,
      "appearances": 1536
    },
    {
      "name": "yoru",
      "pick_rate": 59.9,
      "max_pick_rate": 100.0,
      "avg_rating": 1.01,
      "avg_acs": 210.8,
      "appearances": 2157
    }
  ],
  "economy": {
    "rounds": {
      "Eco: 0-5k": {
        "Loss": 1178,
        "Win": 659,
        "Win Rate %": 35.87
      },
      "Full buy: 20k+": {
        "Loss": 3346,
        "Win": 4123,
        "Win Rate %": 55.2
      },
      "Semi-buy: 10-20k": {
        "Loss": 1235,
        "Win": 1371,
        "Win Rate %": 52.61
      },
      "Semi-eco: 5-10k": {
        "Loss": 545,
        "Win": 151,
        "Win Rate %": 21.7
      }
    }
  },
  "players": [
    {
      "name": "johnqt",
      "team": "Sentinels",
      "rating": 1.34,
      "acs": 226.4,
      "rounds": 544,
      "clutches": 26
    },
    {
      "name": "hiro",
      "team": "Natus Vincere",
      "rating": 1.32,
      "acs": 243.8,
      "rounds": 712,
      "clutches": 32
    },
    {
      "name": "marteen",
      "team": "Gentle Mates",
      "rating": 1.31,
      "acs": 256.6,
      "rounds": 1195,
      "clutches": 28
    },
    {
      "name": "vo0kashu",
      "team": "Dragon Ranger Gaming",
      "rating": 1.22,
      "acs": 218.9,
      "rounds": 875,
      "clutches": 0
    },
    {
      "name": "AAAAY",
      "team": "FunPlus Phoenix",
      "rating": 1.22,
      "acs": 205.2,
      "rounds": 390,
      "clutches": 0
    },
    {
      "name": "happywei",
      "team": "Xi Lai Gaming",
      "rating": 1.21,
      "acs": 224.0,
      "rounds": 1104,
      "clutches": 2
    },
    {
      "name": "primmie",
      "team": "FULL SENSE",
      "rating": 1.19,
      "acs": 247.8,
      "rounds": 404,
      "clutches": 10
    },
    {
      "name": "Yuicaw",
      "team": "JDG Esports",
      "rating": 1.19,
      "acs": 209.2,
      "rounds": 1163,
      "clutches": 0
    },
    {
      "name": "Demon1",
      "team": "Cloud9, ENVY",
      "rating": 1.19,
      "acs": 244.5,
      "rounds": 267,
      "clutches": 2
    },
    {
      "name": "seven",
      "team": "PCIFIC Esports",
      "rating": 1.18,
      "acs": 229.8,
      "rounds": 446,
      "clutches": 4
    },
    {
      "name": "dgzin",
      "team": "Evil Geniuses",
      "rating": 1.16,
      "acs": 234.8,
      "rounds": 813,
      "clutches": 6
    },
    {
      "name": "Demon1",
      "team": "Cloud9",
      "rating": 1.15,
      "acs": 246.0,
      "rounds": 145,
      "clutches": 0
    },
    {
      "name": "bang",
      "team": "100 Thieves",
      "rating": 1.15,
      "acs": 192.6,
      "rounds": 1367,
      "clutches": 22
    },
    {
      "name": "Karon",
      "team": "Gen.G",
      "rating": 1.15,
      "acs": 216.9,
      "rounds": 839,
      "clutches": 36
    },
    {
      "name": "lukxo",
      "team": "LOUD",
      "rating": 1.13,
      "acs": 229.2,
      "rounds": 481,
      "clutches": 3
    }
  ],
  "nongshim": {
    "matches": [
      {
        "match_name": "Nongshim RedForce vs Gentle Mates",
        "tournament": "Valorant Masters Santiago 2026",
        "stage": "Playoffs",
        "opponent": "Gentle Mates",
        "ns_score": 2,
        "opp_score": 0,
        "outcome": "Win"
      },
      {
        "match_name": "Nongshim RedForce vs G2 Esports",
        "tournament": "Valorant Masters Santiago 2026",
        "stage": "Playoffs",
        "opponent": "G2 Esports",
        "ns_score": 2,
        "opp_score": 1,
        "outcome": "Win"
      },
      {
        "match_name": "Nongshim RedForce vs NRG",
        "tournament": "Valorant Masters Santiago 2026",
        "stage": "Playoffs",
        "opponent": "Mega Minors",
        "ns_score": 2,
        "opp_score": 0,
        "outcome": "Win"
      },
      {
        "match_name": "Nongshim RedForce vs Paper Rex",
        "tournament": "Valorant Masters Santiago 2026",
        "stage": "Playoffs",
        "opponent": "Paper Rex",
        "ns_score": 3,
        "opp_score": 0,
        "outcome": "Win"
      },
      {
        "match_name": "Nongshim RedForce vs Team Secret",
        "tournament": "VCT 2026: Pacific Kickoff",
        "stage": "Main Event",
        "opponent": "Team Secret",
        "ns_score": 2,
        "opp_score": 0,
        "outcome": "Win"
      },
      {
        "match_name": "T1 vs Nongshim RedForce",
        "tournament": "VCT 2026: Pacific Kickoff",
        "stage": "Main Event",
        "opponent": "T1",
        "ns_score": 2,
        "opp_score": 1,
        "outcome": "Win"
      },
      {
        "match_name": "Nongshim RedForce vs FULL SENSE",
        "tournament": "VCT 2026: Pacific Kickoff",
        "stage": "Main Event",
        "opponent": "FULL SENSE",
        "ns_score": 2,
        "opp_score": 0,
        "outcome": "Win"
      },
      {
        "match_name": "Nongshim RedForce vs Rex Regum Qeon",
        "tournament": "VCT 2026: Pacific Kickoff",
        "stage": "Main Event",
        "opponent": "Rex Regum Qeon",
        "ns_score": 3,
        "opp_score": 2,
        "outcome": "Win"
      }
    ],
    "players": [
      {
        "name": "Dambi",
        "rating": 1.05,
        "acs": 231.6,
        "rounds": 1673
      },
      {
        "name": "Francis",
        "rating": 1.04,
        "acs": 225.2,
        "rounds": 930
      },
      {
        "name": "Ivy",
        "rating": 1.05,
        "acs": 192.9,
        "rounds": 1819
      },
      {
        "name": "Rb",
        "rating": 1.11,
        "acs": 184.6,
        "rounds": 1591
      },
      {
        "name": "Xross",
        "rating": 1.11,
        "acs": 200.1,
        "rounds": 1819
      }
    ]
  }
};
